# Enphase energy credentials
ENPHASE_API_KEY = "<API KEY>"
ENPHASE_API_ID = "<API ID>"
ENPHASE_USER_ID = "<USER ID>"
ENPHASE_SITE_ID = "<SITE ID>"
ENPHASE_URL = "<ENPHASE URL>"
ENPHASE_DATABASE = "<TINY DB NAME>
ENPHASE_DATABASE_GEN_TABLE = "<TINY DB GENERATION TABLE NAME>"
ENPHASE_DATABASE_CONS_TABLE = "<TINY DB CONSUMPTION TABLE NAME>"


# Flume water meter credentials
FLUME_CLIENT_ID = "<CLIENT ID>"
FLUME_CLIENT_SECRET = "<CLIENT SECRET>"
FLUME_USERNAME = "<EMAIL>"
FLUME_PASSWORD = "<PASSWORD>"
FLUME_LOG = "<LOG FILE>"
FLUME_TOKEN = "<TOKEN>"
