# Enphase energy credentials
ENPHASE_API_KEY = "<API KEY>"
ENPHASE_API_ID = "<API ID>"
ENPHASE_USER_ID = "<USER ID>"
ENPHASE_SITE_ID = "<SITE ID>"
ENPHASE_URL = "<ENPHASE URL>"
ENPHASE_DATABASE = "<TINY DB NAME>"
ENPHASE_DATABASE_GEN_TABLE = "<TINY DB GENERATION TABLE NAME>"
ENPHASE_DATABASE_CONS_TABLE = "<TINY DB CONSUMPTION TABLE NAME>"


# Flume water meter credentials
FLUME_CLIENT_ID = "12345ABCD6EFG7H"
FLUME_CLIENT_SECRET = "ABC123D456EFGHI"
FLUME_USERNAME = "flume.login.email@gmail.com"
FLUME_PASSWORD = "flume_acct_password"
FLUME_LOG = ""
FLUME_TOKEN = ""
